### ISSUE TITLE
;foreach does not work when containers are viewed with Sortedview Flag ON

### ISSUE THREAD

**Issue by HashWrangler** [dewiniaid/gs4-lich-scripts#1]
Hey there.  Love the script.  However, is there any chance that the script can be made to work when using the sortedview flag SET to ON?  Right now, the script breaks using types like gem.

**Comment by dewiniaid** [comment]
Hmm, I never really looked at Sortedview before.

It looks like Sortedview doesn't affect the container windows, which is what Lich uses to update container inventories and ;foreach uses in turn.  (;Foreach doesn't actually care what the `look` command outputs)

So this should be simple enough to fix -- I just need to figure out a suitable pattern that matches what Sortedview sends.  I won't be available much tomorrow though, so a fix probably won't happen until Monday.

If you're running 0.5 (likely, because you found the GitHub issues!), `;foreach ... in inv` uses a different mechanism to identify your inventory so might be a suitable workaround until I can fix it.

**Comment by dewiniaid** [comment]
Fixed in 98ee475f657236907a4f9c7ba60f028957faa0d0
Released as version 0.5.2
